test = {   'name': 'q1_5',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> sum_a == 2532\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> sum_a\n2532',
                                       'hidden': True,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
