test = {   'name': 'q23',
    'points': 3,
    'suites': [   {   'cases': [   {   'code': '>>> len(list(df.index)) == 7\n'
                                               'True',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> df.iloc[0, 0] == 16\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> df.iloc[1, 0] == 3\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
