test = {   'name': 'q1_3',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> len(a2) == 89\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> len(a2) == 85\nFalse',
                                       'hidden': True,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
