test = {   'name': 'q1a',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> df_SP500.shape\n(1114, 7)',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> df_Gold.shape\n(609, 5)',
                                       'hidden': True,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
