test = {   'name': 'q3a2',
    'points': 2,
    'suites': [   {   'cases': [   {   'code': '>>> C == 1e-3\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> test_size == 0.2\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
