test = {   'name': 'q1c',
    'points': 5,
    'suites': [   {   'cases': [   {   'code': '>>> len(X) == 768\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> len(X.columns) == 8\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> len(Y) == 768\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
